blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed


app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="post-list"),
    path("tag/<slug:tag_slug>/", views.PostListView.as_view(), name="post-list-by-tag"),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", views.post_detail, name="post-detail"),
    path("<int:post_id>/share/", views.EmailPostView.as_view(), name="post-share"),
    path("<int:post_id>/comment/", views.CommentView.as_view(), name="post-comment"),
    path("feed/", LatestPostsFeed(), name="post-feed"),
    path("search/", views.post_search, name="post-search"),
]

main/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import TemplateView

from blog.sitemaps import PostSitemap
from pages.views import IndexNow
from tools.sitemaps import ToolSitemap


sitemaps = {"posts": PostSitemap, "tools": ToolSitemap}


urlpatterns = [
    path("private/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("users.urls"), name="users"),
    path("blog/", include("blog.urls", namespace="blog")),
    path("tools/", include("tools.urls", namespace="tools")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path(f"{settings.INDEXNOW_KEY}.txt", IndexNow.as_view(), name="indexnow"),
    path("", include("pages.urls", namespace="pages")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # Add routes to test error templates
    urlpatterns += [
        path("test404/", TemplateView.as_view(template_name="404.html")),
        path("test500/", TemplateView.as_view(template_name="500.html")),
        path("styleguide/", TemplateView.as_view(template_name="styleguide.html")),
    ]


if not settings.TESTING:
    urlpatterns = [*urlpatterns] + debug_toolbar_urls()

tools/urls.py
from django.urls import path

from . import views


app_name = "tools"

urlpatterns = [
    path("", views.ToolListView.as_view(), name="tool-list"),
    path("search/", views.tool_search, name="tool-search"),
    path("tag/<slug:tag_slug>/", views.ToolListView.as_view(), name="tool-list-by-tag"),
    path("category/<slug:category_slug>/", views.ToolListView.as_view(), name="tool-list-by-category"),
    path("<slug:tool_slug>/", views.ToolDetailView.as_view(), name="tool-detail"),
    path("<slug:tool_slug>/report/", views.ToolErrorView.as_view(), name="tool-error"),
]

tools/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Tool.Status.PUBLISHED)


class Category(models.Model):
    name = models.CharField(max_length=80)
    slug = models.SlugField(max_length=80, unique=True)

    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy("tools:tool-list-by-category", args=[self.slug])


class Tool(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    body = models.TextField()
    template_fragment = models.CharField(max_length=250, blank=True)
    js_path = models.CharField(max_length=250, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        verbose_name = _("tool")
        verbose_name_plural = _("tools")
        ordering = ["-publish"]
        indexes = [models.Index(fields=["-publish"])]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy("tools:tool-detail", args=[self.slug])

    def get_error_url(self):
        return reverse_lazy("tools:tool-error", args=[self.slug])

tools/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _


class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control form-control-lg"}))


class ToolErrorForm(forms.Form):
    name = forms.CharField(
        max_length=25,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    email = forms.EmailField(required=False, widget=forms.TextInput(attrs={"class": "form-control"}))
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "cols": 80,
                "rows": 4,
                "placeholder": _("What error are your facing?"),
                "class": "form-control",
            }
        ),
    )

    def send_mail(self):
        cd = self.cleaned_data
        tool = self.tool

        subject = f"Error reported for {tool.name}"
        message = f"Name:{cd['name']}\nEmail:{cd['email']}\nSlug:{tool.get_absolute_url()}\nMessage:{cd['message']}"

        return send_mail(
            subject=subject,
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.DEFAULT_TO_EMAIL],
        )

tools/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import DetailView, FormView, ListView
from taggit.models import Tag

from .forms import SearchForm, ToolErrorForm
from .models import Category, Tool


class HomePageView(ListView):
    """
    Simple view to render on the home page of our project.
    """

    model = Tool
    template_name = "tools/tool_home.html"
    context_object_name = "tools"


class ToolListView(ListView):
    model = Tool
    template_name = "tools/tool_list.html"
    context_object_name = "tools"

    def get_queryset(self):
        qs = Tool.published.all()

        tag_slug = self.kwargs.get("tag_slug")
        category_slug = self.kwargs.get("category_slug")

        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            qs = qs.filter(tags__in=[tag])
            self.extra_context = {"tag": tag}

        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            qs = qs.filter(category=category)
            self.extra_context = {"category": category}

        return qs


class ToolDetailView(DetailView):
    template_name = "tools/tool_detail.html"
    model = Tool
    slug_url_kwarg = "tool_slug"


def tool_search(request):
    form = SearchForm()
    query = request.GET.get("query", None)
    results = []

    if query:
        form = SearchForm(request.GET)
        results = Tool.published.filter(Q(name__icontains=query) | Q(body__icontains=query))
    else:
        results = []

    context = {
        "form": form,
        "query": query,
        "results": results,
    }

    return render(request, "tools/tool_search.html", context)


class ToolErrorView(SuccessMessageMixin, FormView):
    form_class = ToolErrorForm
    template_name = "tools/tool_error.html"
    success_message = "Message sent successfully"

    def get_object(self):
        tool_slug = self.kwargs.get("tool_slug")
        tool = get_object_or_404(Tool, slug=tool_slug, status=Tool.Status.PUBLISHED)
        return tool

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tool"] = self.get_object()
        return context

    def get_success_url(self):
        return reverse_lazy("tools:tool-list")

    def form_valid(self, form):
        form.tool = self.get_object()
        form.send_mail()
        return super().form_valid(form)

tools/templates/tools/tool_detail.html
{% extends "base.html" %}

{% block title %}
  {{ tool.name }}
{% endblock title %}
{% block content %}
  {% if tool.category %}
    <small><a href="{% url 'tools:tool-list' %}">Back</a></small>
  {% endif %}
  <h1>{{ tool.name }}</h1>
  <small>
    {% for tag in tool.tags.all %}
      <a href="{% url 'tools:tool-list-by-tag' tag.slug %}">{{ tag|title }}</a>
      {% if not forloop.last %},{% endif %}
    {% endfor %}
  </small>
  <p>
    <small>Published {{ tool.publish }}</small>
  </p>
  <section>
    <p class="lead">{{ tool.body }}</p>
  </section>
  {% if tool.template_fragment %}
    <section>
      {% include tool.template_fragment %}
    </section>
  {% endif %}
  <ul>
    <li>
      <a href="{{ tool.get_error_url }}">Report an error</a>
    </li>
  </ul>
{% endblock content %}
{% block js %}
  {% if tool.js_path %}<script src={{ tool.js_path }} defer></script>{% endif %}
{% endblock js %}

tools/templates/tools/tool_error.html
{% extends "base.html" %}

{% block title %}
  Report an Error
{% endblock title %}
{% block content %}
  <small><a href="{{ tool.get_absolute_url }}">Back</a></small>
  <h1>Report an error</h1>
  <p>You are reporting an error for the tool "{{ tool.name }}"</p>
  <form method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="mb-3">
        <span class="text-danger">{{ field.errors }}</span>
        <label class="form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
        {{ field }}
        <div class="form-text" id="{{ field.auto_id }}_helptext">
          <small>{{ field.help_text|safe }}</small>
        </div>
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Send</button>
  </form>
{% endblock content %}

tools/templates/tools/tool_home.html
{% extends "base.html" %}

{% block title %}
  Tools Observatory
{% endblock title %}
{% block content %}
  <h1>Tools Observatory</h1>
  <ul>
    {% for tool in tools %}
      <li>
        <a href="{{ tool.get_absolute_url }}">{{ tool.name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

tools/templates/tools/tool_list.html
{% extends "base.html" %}

{% block title %}
  Tool List
{% endblock title %}
{% block content %}
  <h1>All Tools</h1>
  <hr />
  <p>
    <abbr><a href="{% url 'tools:tool-search' %}">Search</a></abbr>
  </p>
  {% if tag %}<h2>Tools tagged with "{{ tag.name }}"</h2>{% endif %}
  {% if category %}<h2>Category "{{ category.name }}"</h2>{% endif %}
  {% for tool in tools %}
    <h2>
      <a href="{{ tool.get_absolute_url }}">{{ tool.name }}</a>
    </h2>
    <small>
      {% for tag in tool.tags.all %}
        <a href="{% url 'tools:tool-list-by-tag' tag.slug %}">{{ tag|title }}</a>
        {% if not forloop.last %},{% endif %}
      {% endfor %}
    </small>
    {{ tool.body|truncatewords:30|linebreaks }}
  {% endfor %}
{% endblock content %}

tools/templates/tools/tool_search.html
{% extends "base.html" %}

{% block title %}
  Search for a tool
{% endblock title %}
{% block content %}
  <section>
    <h1>Search for tools</h1>
    <form method="get">
      {% for field in form.visible_fields %}
        <div class="mb-3">
          <label class="form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
          {{ field }}
        </div>
      {% endfor %}
      <button class="btn btn-primary" type="submit">Search</button>
    </form>
  </section>
  <section class="mt-3">
    {% if query %}
      <h2>Tools containg "{{ query }}"</h2>
      {% with total_results=results.count %}
        <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
        <hr />
      {% endwith %}
    {% endif %}
  </section>
  <section>
    {% for tool in results %}
      <h4>
        <a href="{{ tool.get_absolute_url }}">{{ tool.name }}</a>
      </h4>
      <p>{{ tool.body }}</p>
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
  </section>
{% endblock content %}