blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed


app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="post-list"),
    path("tag/<slug:tag_slug>/", views.PostListView.as_view(), name="post-list-by-tag"),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", views.post_detail, name="post-detail"),
    path("<int:post_id>/share/", views.EmailPostView.as_view(), name="post-share"),
    path("<int:post_id>/comment/", views.CommentView.as_view(), name="post-comment"),
    path("feed/", LatestPostsFeed(), name="post-feed"),
    path("search/", views.post_search, name="post-search"),
]

main/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import TemplateView

from blog.sitemaps import PostSitemap
from pages.views import IndexNow
from tools.sitemaps import ToolSitemap


sitemaps = {"posts": PostSitemap, "tools": ToolSitemap}


urlpatterns = [
    path("private/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("users.urls"), name="users"),
    path("blog/", include("blog.urls", namespace="blog")),
    path("tools/", include("tools.urls", namespace="tools")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path(f"{settings.INDEXNOW_KEY}.txt", IndexNow.as_view(), name="indexnow"),
    path("", include("pages.urls", namespace="pages")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # Add routes to test error templates
    urlpatterns += [
        path("test404/", TemplateView.as_view(template_name="404.html")),
        path("test500/", TemplateView.as_view(template_name="500.html")),
        path("styleguide/", TemplateView.as_view(template_name="styleguide.html")),
    ]


if not settings.TESTING:
    urlpatterns = [*urlpatterns] + debug_toolbar_urls()

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from taggit.managers import TaggableManager


CustomUser = get_user_model()


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        verbose_name = _("post")
        verbose_name_plural = _("posts")
        ordering = ["-publish"]
        indexes = [models.Index(fields=["-publish"])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post-detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    def get_share_url(self):
        return reverse("blog:post-share", args=[self.id])

    def get_comment_url(self):
        return reverse("blog:post-comment", args=[self.id])


class Comment(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("comment")
        verbose_name_plural = _("comments")

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from django.core.mail import send_mail

from .models import Comment


class SearchForm(forms.Form):
    query = forms.CharField()


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

    def send_mail(self):
        cd = self.cleaned_data
        post = self.post
        post_url = self.post_url

        subject = f"{cd['name']} recommends you read {post.title}..."
        message = f"Read {post.title} at {post_url}\n\nComments: {cd['comments']}"

        return send_mail(subject=subject, message=message, from_email=cd["email"], recipient_list=[cd["to"]])


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]

blog/views.py
import logging

from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Count
from django.shortcuts import get_object_or_404, render
from django.views.generic import FormView, ListView
from taggit.models import Tag

from .forms import CommentForm, EmailPostForm, SearchForm
from .models import Post


logger = logging.getLogger(__name__)


class PostListView(ListView):
    context_object_name = "posts"
    paginate_by = 3
    template_name = "blog/post_list.html"

    def get_queryset(self):
        qs = Post.published.all()

        tag_slug = self.kwargs.get("tag_slug")
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            qs = qs.filter(tags__in=[tag])
            self.extra_context = {"tag": tag}

        return qs


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    comments = post.comments.filter(active=True)

    # Build similar posts
    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by("-same_tags", "-publish")

    context = {"comments": comments, "post": post, "similar_posts": similar_posts}

    return render(request, "blog/post_detail.html", context)


class EmailPostView(SuccessMessageMixin, FormView):
    form_class = EmailPostForm
    template_name = "blog/post_share.html"
    success_message = "E-mail sent successfully"

    def get_object(self):
        post_id = self.kwargs.get("post_id")
        post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
        return post

    def form_valid(self, form):
        post = self.get_object()
        post_url = self.request.build_absolute_uri(post.get_absolute_url())

        form.post = post
        form.post_url = post_url
        form.send_mail()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = self.get_object()
        return context

    def get_success_url(self):
        post = self.get_object()
        return post.get_absolute_url()


class CommentView(FormView):
    template_name = "blog/post_comment.html"
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = self.get_object()
        return context

    def form_valid(self, form):
        post = self.get_object()
        form.instance.post = post
        form.save()
        return super().form_valid(form)

    def get_object(self):
        post_id = self.kwargs.get("post_id")
        post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
        return post

    def get_success_url(self):
        post = self.get_object()
        return post.get_absolute_url()


def post_search(request):
    form = SearchForm()
    query = request.GET.get("query", None)
    results = []

    if query:
        form = SearchForm(request.GET)
        results = Post.published.filter(title__icontains=query)
    else:
        results = []

    context = {
        "form": form,
        "query": query,
        "results": results,
    }

    return render(request, "blog/post_search.html", context)

blog/templates/blog/post_comment.html
{% extends "base.html" %}

{% block title %}Add a new comment{% endblock %}
{% block content %}
  <p>
    <a href="{{ post.get_absolute_url }}">Back</a>
  </p>
  <h1>Add a new comment</h1>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Post Comment</button>
  </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
  <p>
    <a href="{% url 'blog:post-list' %}">Back</a>
  </p>
  <h1>{{ post.title }}</h1>
  <small>
    {% for tag in post.tags.all %}
      <a href="{% url 'blog:post-list-by-tag' tag.slug %}">{{ tag|title }}</a>
      {% if not forloop.last %},{% endif %}
    {% endfor %}
  </small>
  <p>
    <small>Published {{ post.publish }} by {{ post.author }}</small>
  </p>
  <section>
    {{ post.body|markdown }}
  </section>
  <section>
    <ul>
      <li>
        <a href="{{ post.get_share_url }}">Share this post</a>
      </li>
      <li>
        <a href="{{ post.get_comment_url }}">Add a comment</a>
      </li>
    </ul>
  </section>
  <section>
    <h2>Similar posts</h2>
    <ul>
      {% for post in similar_posts %}
        <li>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
      {% empty %}
        <p>There are no similar posts yet.</p>
      {% endfor %}
    </ul>
  </section>
  <section>
    <h2>Comments</h2>
    {% for comment in comments %}
      <small>{{ comment.name }} on {{ comment.created }}</small>
      {{ comment.body|linebreaks }}
    {% empty %}
      <p>There are no comments</p>
    {% endfor %}
  </section>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block title %}
  My Blog
{% endblock title %}
{% block content %}
  <h1>My Blog</h1>
  <hr />
  <p>
    <abbr><a href="{% url 'blog:post-feed' %}">Rss</a></abbr>
    <abbr><a href="{% url 'blog:post-search' %}">Search</a></abbr>
  </p>
  {% if tag %}<h2>Posts tagged with "{{ tag.name }}"</h2>{% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h2>
    <small>
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post-list-by-tag' tag.slug %}">{{ tag|title }}</a>
        {% if not forloop.last %},{% endif %}
      {% endfor %}
    </small>
    <p>
      <small>Published {{ post.publish }} by {{ post.author }}</small>
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "includes/pagination.html" with page=page_obj %}
{% endblock content %}

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% load blog_tags %}

{% block title %}Search for a post{% endblock %}
{% block content %}
  <section>
    <h1>Search for posts</h1>
    <form method="get">
      {{ form }}
      <button type="submit">Search</button>
    </form>
  </section>
  <section>
    {% if query %}
      <h2>Posts containg "{{ query }}"</h2>
      {% with total_results=results.count %}
        <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
        <hr />
      {% endwith %}
    {% endif %}
    {% for post in results %}
      <h4>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </h4>
      {{ post.body|markdown|truncatewords_html:12 }}
      <hr />
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
  </section>
{% endblock %}

blog/templates/blog/post_share.html
{% extends "base.html" %}

{% block title %}Share a post{% endblock %}
{% block content %}
  <p>
    <a href="{{ post.get_absolute_url }}">Back</a>
  </p>
  <h1>Share "{{ post.title }}" by e-mail</h1>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Share</button>
  </form>
{% endblock %}